// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnS7JbPd55xOviKwV1sE_E3qpwI4UqflM',
    appId: '1:490665713178:web:d360532050fa1b666afba3',
    messagingSenderId: '490665713178',
    projectId: 'picos-push-notification-ios',
    authDomain: 'picos-push-notification-ios.firebaseapp.com',
    storageBucket: 'picos-push-notification-ios.appspot.com',
    measurementId: 'G-MJTQC5GD4Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTHiACAGFg_vv4a9iomu0oG2VnGDJsi3U',
    appId: '1:490665713178:android:2d99dc8a50bd79ac6afba3',
    messagingSenderId: '490665713178',
    projectId: 'picos-push-notification-ios',
    storageBucket: 'picos-push-notification-ios.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKwcvzXMi55kAuaG4-YM9MQfvhpn49v5w',
    appId: '1:490665713178:ios:7f963e3279e9218e6afba3',
    messagingSenderId: '490665713178',
    projectId: 'picos-push-notification-ios',
    storageBucket: 'picos-push-notification-ios.appspot.com',
    iosBundleId: 'de.hit-solutions.PICOS',
  );
}
